name: alert_v1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^14.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "C:/Users/vicks/StudioProjects\alert_v1\asset/icon"

flutter:
  uses-material-design: true
